apiVersion: release-notes/v2
kind: feature
area: traffic-management

# releaseNotes is a markdown listing of any user facing changes. This will appear in the
# release notes.
releaseNotes:
  - |
    **Fixed** VirtualService `HTTPRetry.attempts` field is no longer a required field.
