# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: istio.io/extensions/field_feature.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import descriptor_pb2 as google_dot_protobuf_dot_descriptor__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='istio.io/extensions/field_feature.proto',
  package='istio.extensions',
  syntax='proto3',
  serialized_options=_b('Z istio.io/api/istio.io/extensions'),
  serialized_pb=_b('\n\'istio.io/extensions/field_feature.proto\x12\x10istio.extensions\x1a google/protobuf/descriptor.proto\"k\n\x0cIstioFeature\x12\x18\n\x06status\x18\x01 \x01(\tH\x00R\x06status\x12\x14\n\x04name\x18\x02 \x01(\tH\x01R\x04name\x12\x10\n\x02id\x18\x03 \x01(\tH\x02R\x02idB\t\n\x07_statusB\x07\n\x05_nameB\x05\n\x03_id:X\n\x07\x66\x65\x61ture\x12\x1d.google.protobuf.FieldOptions\x18\x94\n \x01(\x0b\x32\x1e.istio.extensions.IstioFeatureR\x07\x66\x65\x61tureB\"Z istio.io/api/istio.io/extensionsb\x06proto3')
  ,
  dependencies=[google_dot_protobuf_dot_descriptor__pb2.DESCRIPTOR,])


FEATURE_FIELD_NUMBER = 1300
feature = _descriptor.FieldDescriptor(
  name='feature', full_name='istio.extensions.feature', index=0,
  number=1300, type=11, cpp_type=10, label=1,
  has_default_value=False, default_value=None,
  message_type=None, enum_type=None, containing_type=None,
  is_extension=True, extension_scope=None,
  serialized_options=None, json_name='feature', file=DESCRIPTOR)


_ISTIOFEATURE = _descriptor.Descriptor(
  name='IstioFeature',
  full_name='istio.extensions.IstioFeature',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='istio.extensions.IstioFeature.status', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='status', file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='name', full_name='istio.extensions.IstioFeature.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='name', file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='id', full_name='istio.extensions.IstioFeature.id', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='id', file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='_status', full_name='istio.extensions.IstioFeature._status',
      index=0, containing_type=None, fields=[]),
    _descriptor.OneofDescriptor(
      name='_name', full_name='istio.extensions.IstioFeature._name',
      index=1, containing_type=None, fields=[]),
    _descriptor.OneofDescriptor(
      name='_id', full_name='istio.extensions.IstioFeature._id',
      index=2, containing_type=None, fields=[]),
  ],
  serialized_start=95,
  serialized_end=202,
)

_ISTIOFEATURE.oneofs_by_name['_status'].fields.append(
  _ISTIOFEATURE.fields_by_name['status'])
_ISTIOFEATURE.fields_by_name['status'].containing_oneof = _ISTIOFEATURE.oneofs_by_name['_status']
_ISTIOFEATURE.oneofs_by_name['_name'].fields.append(
  _ISTIOFEATURE.fields_by_name['name'])
_ISTIOFEATURE.fields_by_name['name'].containing_oneof = _ISTIOFEATURE.oneofs_by_name['_name']
_ISTIOFEATURE.oneofs_by_name['_id'].fields.append(
  _ISTIOFEATURE.fields_by_name['id'])
_ISTIOFEATURE.fields_by_name['id'].containing_oneof = _ISTIOFEATURE.oneofs_by_name['_id']
DESCRIPTOR.message_types_by_name['IstioFeature'] = _ISTIOFEATURE
DESCRIPTOR.extensions_by_name['feature'] = feature
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

IstioFeature = _reflection.GeneratedProtocolMessageType('IstioFeature', (_message.Message,), {
  'DESCRIPTOR' : _ISTIOFEATURE,
  '__module__' : 'istio.io.extensions.field_feature_pb2'
  # @@protoc_insertion_point(class_scope:istio.extensions.IstioFeature)
  })
_sym_db.RegisterMessage(IstioFeature)

feature.message_type = _ISTIOFEATURE
google_dot_protobuf_dot_descriptor__pb2.FieldOptions.RegisterExtension(feature)

DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
