// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: istio.io/extensions/field_feature.proto

package extensions

import (
	bytes "bytes"
	fmt "fmt"
	github_com_gogo_protobuf_jsonpb "github.com/gogo/protobuf/jsonpb"
	proto "github.com/gogo/protobuf/proto"
	_ "github.com/gogo/protobuf/protoc-gen-gogo/descriptor"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// MarshalJSON is a custom marshaler for IstioFeature
func (this *IstioFeature) MarshalJSON() ([]byte, error) {
	str, err := FieldFeatureMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler for IstioFeature
func (this *IstioFeature) UnmarshalJSON(b []byte) error {
	return FieldFeatureUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

var (
	FieldFeatureMarshaler   = &github_com_gogo_protobuf_jsonpb.Marshaler{}
	FieldFeatureUnmarshaler = &github_com_gogo_protobuf_jsonpb.Unmarshaler{AllowUnknownFields: true}
)
